<WaitScreen>:

    on_enter: root.score_update()
    first_place:first_place


    FloatLayout:
        size_hint: None, None


    Label:
        id:first_place
        text: "1st Place: "
        pos_hint:{"x":0,"y": -0.1}
        color: 0, 0, 1, 1
        font_size: 30

    Label:
        id: Leaderboard_Display_Text
        text: "Top Scorers:"
        pos_hint:{"x":0,"y":0.35}
        color: 0,1,0,1
        font_size: 50





